from sqlalchemy import Column, Integer, SmallInteger, TIMESTAMP, Boolean
from datetime import datetime
from .base_model import BaseModel


class AndonPageData(BaseModel):
    __tablename__ = 'andon_page_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    chika = Column(Integer)
    p_f_ow = Column(Integer)
    p_f_ot = Column(Integer)
    toso = Column(Integer)
    _3_kai = Column(Integer)
    fsm_l = Column(Integer)
    fsm_r = Column(Integer)
    ctr_rada = Column(Integer)
    dash = Column(Integer)
    ec_cv = Column(Integer)
    cl_cv = Column(Integer)
    ru_cv = Column(Integer)
    r_f = Column(Integer)
    floor = Column(Integer)
    _5f_670kai = Column(Integer)
    r_u = Column(Integer)
    noa_floor = Column(Integer)
    u_b_kari_zo = Column(Integer)
    s_m_hanso = Column(Integer)
    m_b_kari_tsuki = Column(Integer)
    m_b_zoda = Column(Integer)
    sps = Column(Integer)
    _4ten_agv = Column(Integer)
    roof = Column(Integer)
    inner_l = Column(Integer)
    outer_l = Column(Integer)
    s_m_l = Column(Integer)
    s_m_r = Column(Integer)
    outer_r = Column(Integer)
    inner_r = Column(Integer)
    _2line_keikaku_daisu = Column(Integer)
    _2line_shindo_daisu = Column(Integer)
    _2line_jisseki_daisu = Column(Integer)
    _2line_zangyo_jikan = Column(Integer)
    _1line_keikaku_daisu = Column(Integer)
    _1line_shindo_daisu = Column(Integer)
    _1line_jisseki_daisu = Column(Integer)
    _1line_zangyo_jikan = Column(Integer)
    chika_status = Column(Integer)
    sheru_nai_status = Column(Integer)
    _3kai_nishi_status = Column(Integer)
    _3kai_higashi_status = Column(Integer)
    fsm_l_status = Column(Integer)
    fsm_r_status = Column(Integer)
    r_f_status = Column(Integer)
    e_c_status = Column(Integer)
    _67cr_rada_status = Column(Integer)
    _67_r_u_status = Column(Integer)
    ec_oroshi_status = Column(Integer)
    s_m_hanso_status = Column(Integer)
    s_m_cv_status = Column(Integer)
    s_m_l_status = Column(Integer)
    s_m_r_status = Column(Integer)
    inner_l_status = Column(Integer)
    outer_l_status = Column(Integer)
    outer_r_status = Column(Integer)
    inner_r_status = Column(Integer)
    noa_roof_status = Column(Integer)
    u_b_kari_zo_status = Column(Integer)
    m_b_kari_tsuki_status = Column(Integer)
    m_b_zoda_status = Column(Integer)
    S_B_storage_CV_status = Column(Integer)
    dai1sheru_status = Column(Integer)
    dai2sheru_status = Column(Integer)
    p_f_ow_status = Column(Integer)
    p_f_ot_status = Column(Integer)
    _4ten_hanso_status = Column(Integer)
    roof_agv_status = Column(Integer)
    agv_status = Column(Integer)
    _3f_shikake_status = Column(Integer)
    _4f_shikake_status = Column(Integer)
    s_m3_l_status = Column(Integer)
    s_m3_r_status = Column(Integer)
    s_d_l_status = Column(Integer)
    food_status = Column(Integer)
    rsm_status = Column(Integer)
    u_b3_l_status = Column(Integer)
    u_b3_r_status = Column(Integer)
    _5f_670kai_status = Column(Integer)
    dash_status = Column(Integer)
    rajisapo_status = Column(Integer)
    rokkamenba_status = Column(Integer)
    f_d_l_status = Column(Integer)
    f_d_r_status = Column(Integer)
    s_d_r_status = Column(Integer)
    b_d_status = Column(Integer)
    sps_status = Column(Integer)
    _2sheru_status = Column(Integer)
    _1sheru_status = Column(Integer)
    chu2kai_goguchi_status = Column(Integer)
    chu2kai_retsugai_status = Column(Integer)
    retsugaito_nyujo_status = Column(Integer)
    _3kai_toso_status = Column(Integer)
    Fender_status = Column(Integer)
    _3_reikyaku_mizu_ponpu_status = Column(Integer)
    _4_reikyaku_mizu_ponpu_status = Column(Integer)
    Gas_atsu_status = Column(Integer)
    Choko_kanri_status = Column(Integer)
    floor_status = Column(Integer)
    ec_cv_status = Column(Integer)
    cl_cv_status = Column(Integer)
    ru_cv_status = Column(Integer)
    E_C_hanso_status = Column(Integer)
    CTR_hanso_status = Column(Integer)
    R_U_hanso_status = Column(Integer)
    _5f_97kai_status = Column(Integer)
    _970fsm_r_status = Column(Integer)
    _970_ap_fsm_status = Column(Integer)
    _970fsm_l_status = Column(Integer)
    _970rajisapo_status = Column(Integer)
    _970dash_status = Column(Integer)   # error
    _970ctr_rada_status = Column(Integer)
    _970_ru_status = Column(Integer)
    _970_ec_status = Column(Integer)
    Trigger = Column(Integer)
 



    