from sqlalchemy import Column, Integer, SmallInteger, TIMESTAMP, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime
from .base_model import BaseModel



class AndonPageData(BaseModel):
    __tablename__ = 'andon_page_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    chika = Column(Integer)
    p_f_ow = Column(Integer)
    p_f_ot = Column(Integer)
    toso = Column(Integer)
    _3_kai = Column(Integer)
    fsm_l = Column(Integer)
    fsm_r = Column(Integer)
    ctr_rada = Column(Integer)
    dash = Column(Integer)
    ec_cv = Column(Integer)
    cl_cv = Column(Integer)
    ru_cv = Column(Integer)
    r_f = Column(Integer)
    kai = Column(Integer)
    _5f_670kai = Column(Integer)
    r_u = Column(Integer)
    noa_kai = Column(Integer)
    u_b_kari_zo = Column(Integer)
    s_m_hanso = Column(Integer)
    m_b_kari_tsuki = Column(Integer)
    m_b_zoda = Column(Integer)
    sps = Column(Integer)
    _4ten_agv = Column(Integer)
    roof = Column(Integer)
    inner_l = Column(Integer)
    outer_l = Column(Integer)
    s_m_l = Column(Integer)
    s_m_r = Column(Integer)
    outer_r = Column(Integer)
    inner_r = Column(Integer)
    _2rain_kaikaku_daisu = Column(Integer)
    _2rain_shindo_daisu = Column(Integer)
    _2rain_jisseki_daisu = Column(Integer)
    _2rain_zangyo_jikan = Column(Integer)
    _1rain_kaikaku_daisu = Column(Integer)
    _1rain_shindo_daisu = Column(Integer)
    _1rain_jisseki_daisu = Column(Integer)
    _1rain_zangyo_jikan = Column(Integer)
    sheru_nai = Column(Integer)
    _3kai_nishi = Column(Integer)
    _3kai_azuma = Column(Integer)
    e_c = Column(Integer)
    _67cr_rada = Column(Integer)
    _67_r_u = Column(Integer)
    ec_oroshi = Column(Integer)
    s_m_cv = Column(Integer)
    noal_roof = Column(Integer)
    S_B_storage_CV = Column(Integer)
    dai1sheru_teishi_chu = Column(Integer)
    dai2sheru_teishi_chu = Column(Integer)
    _4ten_hanso = Column(Integer)
    roof_agv = Column(Integer)
    agv = Column(Integer)
    _3f_shikake = Column(Integer)
    _4f_shikake = Column(Integer)
    s_m3_l = Column(Integer)
    s_m3_r = Column(Integer)
    s_d_l = Column(Integer)
    food = Column(Integer)
    rsm = Column(Integer)
    u_b3_l = Column(Integer)
    u_b3_r = Column(Integer)
    rajisapo = Column(Integer)
    rokkamenba = Column(Integer)
    f_d_l = Column(Integer)
    f_d_r = Column(Integer)
    s_d_r = Column(Integer)
    b_d = Column(Integer)
    _2_sheru_ijou = Column(Integer)
    _2_sherubo_ketsu = Column(Integer)
    _2_sherubo_man = Column(Integer)
    _2_sheru_soku_toma = Column(Integer)
    _2_sheru_sagyo_okure = Column(Integer)
    _2_sheru_tei_ichi_teishi = Column(Integer)
    _2_sheru_nazo_teishi = Column(Integer)
    _1_sheru_ijou = Column(Integer)
    _1_sherubo_ketsu = Column(Integer)
    _1_sherubo_man = Column(Integer)
    _1_sheru_soku_toma = Column(Integer)
    _1_sheru_sagyo_okure = Column(Integer)
    _1_sheru_tei_ichi_teishi = Column(Integer)
    _1_sheru_nazo_teishi = Column(Integer)
    SPS_delay_1R_work_delay = Column(Integer)
    Mezzo_floor_entrance = Column(Integer)
    Mezzo_floor_outside_row = Column(Integer)
    Outside_row_input_area = Column(Integer)
    _3rd_floor_painting = Column(Integer)
    Fender = Column(Integer)
    _3_reikyaku_mizu_ponpu = Column(Integer)
    _4_reikyaku_mizu_ponpu = Column(Integer)
    Gas_atsu = Column(Integer)
    Indication_management = Column(Integer)
    E_C_transport = Column(Integer)
    CTR_transport = Column(Integer)
    R_U_transport = Column(Integer)
    _5_kai_97_kai = Column(Integer)
    Outside_row_removal = Column(Integer)
    _2_shell_lifter_immediately_stopped = Column(Integer)
    _970fsm_r = Column(Integer)
    _970_ap_fsm = Column(Integer)
    _970fsm_l = Column(Integer)
    _970radio_support = Column(Integer)
    _970_dash = Column(Integer)
    _970ctr_rada = Column(Integer)
    _970_ru = Column(Integer)
    _970_ec = Column(Integer)
 



    