from sqlalchemy import create_engine, Column, Integer
from .base_model import BaseModel

class SmPageData1(BaseModel):
    __tablename__ = 'sm_page_data1'
    
    id = Column(Integer, primary_key=True)
    smr_daisu = Column(Integer)
    sml_daisu = Column(Integer)
    roof_daisu = Column(Integer)
    header_daisu = Column(Integer)
    outer_r_daisu = Column(Integer)
    outer_l_daisu = Column(Integer)
    smr_em_time = Column(Integer)
    sml_em_time = Column(Integer)
    roof_em_time = Column(Integer)
    header_em_time = Column(Integer)
    outer_r_em_time = Column(Integer)
    outer_l_em_time = Column(Integer)
    smr_boman = Column(Integer)
    sml_boman = Column(Integer)
    roof_boman = Column(Integer)
    header_boman = Column(Integer)
    outer_r_boman = Column(Integer)
    outer_l_boman = Column(Integer)
    smr_boketsu = Column(Integer)
    sml_boketsu = Column(Integer)
    roof_boketsu = Column(Integer)
    header_boketsu = Column(Integer)
    outer_r_boketsu = Column(Integer)
    outer_l_boketsu = Column(Integer)
    smr_shokusei_yobidashi = Column(Integer)
    sml_shokusei_yobidashi = Column(Integer)
    roof_shokusei_yobidashi = Column(Integer)
    header_shokusei_yobidashi = Column(Integer)
    outer_r_shokusei_yobidashi = Column(Integer)
    outer_l_shokusei_yobidashi = Column(Integer)
    smr_sei_yobidashi = Column(Integer)
    sml_sei_yobidashi = Column(Integer)
    roof_sei_yobidashi = Column(Integer)
    header_sei_yobidashi = Column(Integer)
    outer_r_sei_yobidashi = Column(Integer)
    outer_l_sei_yobidashi = Column(Integer)
    
# Define the `sm_page_data2` table
class SmPageData2(BaseModel):
    __tablename__ = 'sm_page_data2'
    
    id = Column(Integer, primary_key=True)
    inner_r_daisu = Column(Integer)
    inner_l_daisu = Column(Integer)
    cprfr_daisu = Column(Integer)
    cprfl_daisu = Column(Integer)
    transport_daisu = Column(Integer)
    inner_r_em_time = Column(Integer)
    inner_l_em_time = Column(Integer)
    cprfr_em_time = Column(Integer)
    cprfl_em_time = Column(Integer)
    transport_em_time = Column(Integer)
    inner_r_boman = Column(Integer)
    inner_l_boman = Column(Integer)
    cprfr_boman = Column(Integer)
    cprfl_boman = Column(Integer)
    transport_boman = Column(Integer)
    inner_r_boketsu = Column(Integer)
    inner_l_boketsu = Column(Integer)
    cprfr_boketsu = Column(Integer)
    cprfl_boketsu = Column(Integer)
    transport_boketsu = Column(Integer)
    inner_r_shokusei_yobidashi = Column(Integer)
    inner_l_shokusei_yobidashi = Column(Integer)
    cprfr_shokusei_yobidashi = Column(Integer)
    cprfl_shokusei_yobidashi = Column(Integer)
    transport_shokusei_yobidashi = Column(Integer)
    inner_r_sei_yobidashi = Column(Integer)
    inner_l_sei_yobidashi = Column(Integer)
    cprfr_sei_yobidashi = Column(Integer)
    cprfl_sei_yobidashi = Column(Integer)
    transport_sei_yobidashi = Column(Integer)
   
