from sqlalchemy import Column, Integer, BigInteger, String, Boolean, SmallInteger, Time, TIMESTAMP, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from base_model import BaseModel



class UnderBodyPageData1(BaseModel):
    __tablename__ = 'under_body_page_data1'
    id = Column(Integer, primary_key=True, autoincrement=True)
    frfr_r_daisu = Column(Integer)
    frfr_l_daisu = Column(Integer)
    apron_r_daisu = Column(Integer)
    apron_l_daisu = Column(Integer)
    inner_r_daisu = Column(Integer)
    inner_l_daisu = Column(Integer)
    frfr_r_em_time = Column(Integer)
    frfr_l_em_time = Column(Integer)
    apron_r_em_time = Column(Integer)
    apron_l_em_time = Column(Integer)
    inner_r_em_time = Column(Integer)
    inner_l_em_time = Column(Integer)
    frfr_r_boman = Column(Integer)
    frfr_l_boman = Column(Integer)
    apron_r_boman = Column(Integer)
    apron_l_boman = Column(Integer)
    inner_r_boman = Column(Integer)
    inner_l_boman = Column(Integer)
    frfr_r_boketsu = Column(Integer)
    frfr_l_boketsu = Column(Integer)
    apron_r_boketsu = Column(Integer)
    apron_l_boketsu = Column(Integer)
    inner_r_boketsu = Column(Integer)
    inner_l_boketsu = Column(Integer)
    frfr_r_shokusei_yobidashi = Column(Integer)
    frfr_l_shokusei_yobidashi = Column(Integer)
    apron_r_shokusei_yobidashi = Column(Integer)
    apron_l_shokusei_yobidashi = Column(Integer)
    inner_r_shokusei_yobidashi = Column(Integer)
    inner_l_shokusei_yobidashi = Column(Integer)
    frfr_r_sei_yobidashi = Column(Integer)
    frfr_l_sei_yobidashi = Column(Integer)
    apron_r_sei_yobidashi = Column(Integer)
    apron_l_sei_yobidashi = Column(Integer)
    inner_r_sei_yobidashi = Column(Integer)
    inner_l_sei_yobidashi = Column(Integer)


# Define the `under_body_page_data2` table
class UnderBodyPageData2(BaseModel):
    __tablename__ = 'under_body_page_data2'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    fsmr_daisu = Column(Integer)
    fsml_daisu = Column(Integer)
    dash_daisu = Column(Integer)
    locker_daisu = Column(Integer)
    rfloor_daisu = Column(Integer)
    fsmr_em_time = Column(Integer)
    fsml_em_time = Column(Integer)
    dash_em_time = Column(Integer)
    locker_em_time = Column(Integer)
    rfloor_em_time = Column(Integer)
    fsmr_boman = Column(Integer)
    fsml_boman = Column(Integer)
    dash_boman = Column(Integer)
    locker_boman = Column(Integer)
    rfloor_boman = Column(Integer)
    fsmr_boketsu = Column(Integer)
    fsml_boketsu = Column(Integer)
    dash_boketsu = Column(Integer)
    locker_boketsu = Column(Integer)
    rfloor_boketsu = Column(Integer)
    fsmr_shokusei_yobidashi = Column(Integer)
    fsml_shokusei_yobidashi = Column(Integer)
    dash_shokusei_yobidashi = Column(Integer)
    locker_shokusei_yobidashi = Column(Integer)
    rfloor_shokusei_yobidashi = Column(Integer)
    fsmr_sei_yobidashi = Column(Integer)
    fsml_sei_yobidashi = Column(Integer)
    dash_sei_yobidashi = Column(Integer)
    locker_sei_yobidashi = Column(Integer)
    rfloor_sei_yobidashi = Column(Integer)

# Define the `under_body_page_data3` table
class UnderBodyPageData3(BaseModel):
    __tablename__ = 'under_body_page_data3'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    noa_e_c_daisu = Column(Integer)
    al_e_c_daisu = Column(Integer)
    noa_ctr_daisu = Column(Integer)
    al_ctr_daisu = Column(Integer)
    noa_r_u_daisu = Column(Integer)
    al_r_u_daisu = Column(Integer)
    noa_e_c_em_time = Column(Integer)
    al_e_c_em_time = Column(Integer)
    noa_ctr_em_time = Column(Integer)
    al_ctr_em_time = Column(Integer)
    noa_r_u_em_time = Column(Integer)
    al_r_u_em_time = Column(Integer)
    noa_e_c_boman = Column(Integer)
    al_e_c_boman = Column(Integer)
    noa_ctr_boman = Column(Integer)
    al_ctr_boman = Column(Integer)
    noa_r_u_boman = Column(Integer)
    al_r_u_boman = Column(Integer)
    noa_e_c_boketsu = Column(Integer)
    al_e_c_boketsu = Column(Integer)
    noa_ctr_boketsu = Column(Integer)
    al_ctr_boketsu = Column(Integer)
    noa_r_u_boketsu = Column(Integer)
    al_r_u_boketsu = Column(Integer)
    noa_e_c_shokusei_yobidashi = Column(Integer)
    al_e_c_shokusei_yobidashi = Column(Integer)
    noa_ctr_shokusei_yobidashi = Column(Integer)
    al_ctr_shokusei_yobidashi = Column(Integer)
    noa_r_u_shokusei_yobidashi = Column(Integer)
    al_r_u_shokusei_yobidashi = Column(Integer)
    noa_e_c_sei_yobidashi = Column(Integer)
    al_e_c_sei_yobidashi = Column(Integer)
    noa_ctr_sei_yobidashi = Column(Integer)
    al_ctr_sei_yobidashi = Column(Integer)
    noa_r_u_sei_yobidashi = Column(Integer)
    al_r_u_sei_yobidashi = Column(Integer)

    # round_master = relationship('RoundMaster', foreign_keys=[round, is_morning])

