from enties.ndai import NdaiPageData
from .base_mapper import BaseMapper


class NdaiPageDataMapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = NdaiPageData()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.sample_kotei_ryuju_no = row.get('sample_kotei_ryuju_no_ndai', 0)
        model_instance.sample_kotei_renban = row.get('sample_kotei_renban_ndai', 0)
        model_instance.sample_kotei_shashu = row.get('sample_kotei_shashu_ndai', 0)
        model_instance.mbm_kotei_ryuju_no = row.get('mbm_kotei_ryuju_no_ndai', 0)
        model_instance.mbm_kotei_renban = row.get('mbm_kotei_renban_ndai', 0)
        model_instance.mbm_kotei_shashu = row.get('mbm_kotei_shashu_ndai', 0)
        model_instance.mbk1kotei_ub_paretto_no = row.get('mbk1kotei_ub_paretto_no_ndai', 0)
        model_instance.mbk1kotei_shashu = row.get('mbk1kotei_shashu_ndai', 0)
        model_instance.mbk1kotei_renban = row.get('mbk1kotei_renban_ndai', 0)
        model_instance.mbk2kotei_dl_matehanshashu = row.get('mbk2kotei_dl_matehanshashu_ndai', 0)
        model_instance.mbk2kotei_renban = row.get('mbk2kotei_renban_ndai', 0)
        model_instance.sm_outer_l1kotei_670_sukitto_no = row.get('sm_outer_l1kotei_670_sukitto_no_ndai', 0)
        model_instance.sm_outer_l1kotei_shashu = row.get('sm_outer_l1kotei_shashu_ndai', 0)
        model_instance.sm_outer_l1kotei_renban = row.get('sm_outer_l1kotei_renban_ndai', 0)
        model_instance.sm_outer_l1kotei_670_shashu = row.get('sm_outer_l1kotei_670_shashu_ndai', 0)
        model_instance.sm_outer_l1kotei_970_shashu = row.get('sm_outer_l1kotei_970_shashu_ndai', 0)
        model_instance.sm_outer_r1kotei_670_sukitto_no = row.get('sm_outer_r1kotei_670_sukitto_no_ndai', 0)
        model_instance.sm_outer_r1kotei_shashu = row.get('sm_outer_r1kotei_shashu_ndai', 0)
        model_instance.sm_outer_r1kotei_renban = row.get('sm_outer_r1kotei_renban_ndai', 0)
        model_instance.sm_outer_r1kotei_670_shashu = row.get('sm_outer_r1kotei_670_shashu_ndai', 0)
        model_instance.sm_outer_r1kotei_970_shashu = row.get('sm_outer_r1kotei_970_shashu_ndai', 0)
        model_instance.sm_sukiba_l_kotei_shashu = row.get('sm_sukiba_l_kotei_shashu_ndai', 0)
        model_instance.sm_sukiba_l_kotei_renban = row.get('sm_sukiba_l_kotei_renban_ndai', 0)
        model_instance.sm_sukiba_l_kotei_sukitto_no = row.get('sm_sukiba_l_kotei_sukitto_no_ndai', 0)
        model_instance.sm_sukiba_r_kotei_shashu = row.get('sm_sukiba_r_kotei_shashu_ndai', 0)
        model_instance.sm_sukiba_r_kotei_renban = row.get('sm_sukiba_r_kotei_renban_ndai', 0)
        model_instance.sm_sukiba_r_kotei_sukitto_no = row.get('sm_sukiba_r_kotei_sukitto_no_ndai', 0)
        model_instance.s_dl_kotei_shashu = row.get('s_dl_kotei_shashu_ndai', 0)
        model_instance.s_dl_kotei_renban = row.get('s_dl_kotei_renban_ndai', 0)
        model_instance.s_dl_kotei_kaiten_jigu_no = row.get('s_dl_kotei_kaiten_jigu_no_ndai', 0)
        model_instance.s_dr_kotei_shashu = row.get('s_dr_kotei_shashu_ndai', 0)
        model_instance.s_dr_kotei_renban = row.get('s_dr_kotei_renban_ndai', 0)
        model_instance.s_dr_kotei_kaiten_jigu_no = row.get('s_dr_kotei_kaiten_jigu_no_ndai', 0)
        model_instance.b_d_kotei_shashu = row.get('b_d_kotei_shashu_ndai', 0)
        model_instance.b_d_kotei_renban = row.get('b_d_kotei_renban_ndai', 0)
        model_instance.b_d_kotei_kaiten_jigu_no = row.get('b_d_kotei_kaiten_jigu_no_ndai', 0)
        model_instance.e_c_kotei_shashu = row.get('e_c_kotei_shashu_ndai', 0)
        model_instance.e_c_kotei_renban = row.get('e_c_kotei_renban_ndai', 0)
        model_instance.e_c_kotei_sukitto_no = row.get('e_c_kotei_sukitto_no_ndai', 0)
        model_instance.rr_u_kotei_shashu = row.get('rr_u_kotei_shashu_ndai', 0)
        model_instance.rr_u_kotei_renban = row.get('rr_u_kotei_renban_ndai', 0)
        model_instance.rr_u_kotei_sukitto_no = row.get('rr_u_kotei_sukitto_no_ndai', 0)
        model_instance.ctrr_kotei_shashu = row.get('ctrr_kotei_shashu_ndai', 0)
        model_instance.ctrr_kotei_renban = row.get('ctrr_kotei_renban_ndai', 0)
        model_instance.ctrr_kotei_sukitto_no = row.get('ctrr_kotei_sukitto_no_ndai', 0)
        # string data
        model_instance.A_ukekoma_data = row.get('A_ukekoma_data_ndai', "")
        model_instance.B_ukekoma_data = row.get('B_ukekoma_data_ndai', "")
        model_instance.C_ukekoma_data = row.get('C_ukekoma_data_ndai', "")
        model_instance.D_ukekoma_data = row.get('D_ukekoma_data_ndai', "")

        return model_instance