from enties.saimen import  SmPageData1, SmPageData2
from .base_mapper import BaseMapper


class SmPageData1Mapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = SmPageData1()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.smr_daisu = row.get('smr_daisu_sm', 0)
        model_instance.sml_daisu = row.get('sml_daisu_sm', 0)
        model_instance.roof_daisu = row.get('roof_daisu_sm', 0)
        model_instance.header_daisu = row.get('header_daisu_sm', 0)
        model_instance.outer_r_daisu = row.get('outer_r_daisu_sm', 0)
        model_instance.outer_l_daisu = row.get('outer_l_daisu_sm', 0)
        model_instance.smr_em_time = row.get('smr_em_time_sm', 0)
        model_instance.sml_em_time = row.get('sml_em_time_sm', 0)
        model_instance.roof_em_time = row.get('roof_em_time_sm', 0)
        model_instance.header_em_time = row.get('header_em_time_sm', 0)
        model_instance.outer_r_em_time = row.get('outer_r_em_time_sm', 0)
        model_instance.outer_l_em_time = row.get('outer_l_em_time_sm', 0)
        model_instance.smr_boman = row.get('smr_boman_sm', 0)
        model_instance.sml_boman = row.get('sml_boman_sm', 0)
        model_instance.roof_boman = row.get('roof_boman_sm', 0)
        model_instance.header_boman = row.get('header_boman_sm', 0)
        model_instance.outer_r_boman = row.get('outer_r_boman_sm', 0)
        model_instance.outer_l_boman = row.get('outer_l_boman_sm', 0)
        model_instance.smr_boketsu = row.get('smr_boketsu_sm', 0)
        model_instance.sml_boketsu = row.get('sml_boketsu_sm', 0)
        model_instance.roof_boketsu = row.get('roof_boketsu_sm', 0)
        model_instance.header_boketsu = row.get('header_boketsu_sm', 0)
        model_instance.outer_r_boketsu = row.get('outer_r_boketsu_sm', 0)
        model_instance.outer_l_boketsu = row.get('outer_l_boketsu_sm', 0)
        model_instance.smr_shokusei_yobidashi = row.get('smr_shokusei_yobidashi_sm', 0)
        model_instance.sml_shokusei_yobidashi = row.get('sml_shokusei_yobidashi_sm', 0)
        model_instance.roof_shokusei_yobidashi = row.get('roof_shokusei_yobidashi_sm', 0)
        model_instance.header_shokusei_yobidashi = row.get('header_shokusei_yobidashi_sm', 0)
        model_instance.outer_r_shokusei_yobidashi = row.get('outer_r_shokusei_yobidashi_sm', 0)
        model_instance.outer_l_shokusei_yobidashi = row.get('outer_l_shokusei_yobidashi_sm', 0)
        model_instance.smr_sei_yobidashi = row.get('smr_sei_yobidashi_sm', 0)
        model_instance.sml_sei_yobidashi = row.get('sml_sei_yobidashi_sm', 0)
        model_instance.roof_sei_yobidashi = row.get('roof_sei_yobidashi_sm', 0)
        model_instance.header_sei_yobidashi = row.get('header_sei_yobidashi_sm', 0)
        model_instance.outer_r_sei_yobidashi = row.get('outer_r_sei_yobidashi_sm', 0)
        model_instance.outer_l_sei_yobidashi = row.get('outer_l_sei_yobidashi_sm', 0)

        return model_instance

class SmPageData2Mapper(BaseMapper):
   def map_to_model(self, row):
        model_instance = SmPageData2()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.inner_r_daisu = row.get('inner_r_daisu_sm', 0)
        model_instance.inner_l_daisu = row.get('inner_l_daisu_sm', 0)
        model_instance.cprfr_daisu = row.get('cprfr_daisu_sm', 0)
        model_instance.cprfl_daisu = row.get('cprfl_daisu_sm', 0)
        model_instance.transport_daisu = row.get('transport_daisu_sm', 0)
        model_instance.inner_r_em_time = row.get('inner_r_em_time_sm', 0)
        model_instance.inner_l_em_time = row.get('inner_l_em_time_sm', 0)
        model_instance.cprfr_em_time = row.get('cprfr_em_time_sm', 0)
        model_instance.cprfl_em_time = row.get('cprfl_em_time_sm', 0)
        model_instance.transport_em_time = row.get('transport_em_time_sm', 0)
        model_instance.inner_r_boman = row.get('inner_r_boman_sm', 0)
        model_instance.inner_l_boman = row.get('inner_l_boman_sm', 0)
        model_instance.cprfr_boman = row.get('cprfr_boman_sm', 0)
        model_instance.cprfl_boman = row.get('cprfl_boman_sm', 0)
        model_instance.transport_boman = row.get('transport_boman_sm', 0)
        model_instance.inner_r_boketsu = row.get('inner_r_boketsu_sm', 0)
        model_instance.inner_l_boketsu = row.get('inner_l_boketsu_sm', 0)
        model_instance.cprfr_boketsu = row.get('cprfr_boketsu_sm', 0)
        model_instance.cprfl_boketsu = row.get('cprfl_boketsu_sm', 0)
        model_instance.transport_boketsu = row.get('transport_boketsu_sm', 0)
        model_instance.inner_r_shokusei_yobidashi = row.get('inner_r_shokusei_yobidashi_sm', 0)
        model_instance.inner_l_shokusei_yobidashi = row.get('inner_l_shokusei_yobidashi_sm', 0)
        model_instance.cprfr_shokusei_yobidashi = row.get('cprfr_shokusei_yobidashi_sm', 0)
        model_instance.cprfl_shokusei_yobidashi = row.get('cprfl_shokusei_yobidashi_sm', 0)
        model_instance.transport_shokusei_yobidashi = row.get('transport_shokusei_yobidashi_sm', 0)
        model_instance.inner_r_sei_yobidashi = row.get('inner_r_sei_yobidashi_sm', 0)
        model_instance.inner_l_sei_yobidashi = row.get('inner_l_sei_yobidashi_sm', 0)
        model_instance.cprfr_sei_yobidashi = row.get('cprfr_sei_yobidashi_sm', 0)
        model_instance.cprfl_sei_yobidashi = row.get('cprfl_sei_yobidashi_sm', 0)
        model_instance.transport_sei_yobidashi = row.get('transport_sei_yobidashi_sm', 0)
        return model_instance

