from enties.under_body import UnderBodyPageData1, UnderBodyPageData2, UnderBodyPageData3, UnderBodyPageData4
from .base_mapper import BaseMapper



class UnderBodyPageData1Mapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = UnderBodyPageData1()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.frfr_r_daisu = row.get('frfr_r_daisu_ub', 0)
        model_instance.frfr_l_daisu = row.get('frfr_l_daisu_ub', 0)
        model_instance.apron_r_daisu = row.get('apron_r_daisu_ub', 0)
        model_instance.apron_l_daisu = row.get('apron_l_daisu_ub', 0)
        model_instance.inner_r_daisu = row.get('inner_r_daisu_ub', 0)
        model_instance.inner_l_daisu = row.get('inner_l_daisu_ub', 0)
        model_instance.frfr_r_em_time = row.get('frfr_r_em_time_ub', 0)
        model_instance.frfr_l_em_time = row.get('frfr_l_em_time_ub', 0)
        model_instance.apron_r_em_time = row.get('apron_r_em_time_ub', 0)
        model_instance.apron_l_em_time = row.get('apron_l_em_time_ub', 0)
        model_instance.inner_r_em_time = row.get('inner_r_em_time_ub', 0)
        model_instance.inner_l_em_time = row.get('inner_l_em_time_ub', 0)
        model_instance.frfr_r_boman = row.get('frfr_r_boman_ub', 0)
        model_instance.frfr_l_boman = row.get('frfr_l_boman_ub', 0)
        model_instance.apron_r_boman = row.get('apron_r_boman_ub', 0)
        model_instance.apron_l_boman = row.get('apron_l_boman_ub', 0)
        model_instance.inner_r_boman = row.get('inner_r_boman_ub', 0)
        model_instance.inner_l_boman = row.get('inner_l_boman_ub', 0)
        model_instance.frfr_r_boketsu = row.get('frfr_r_boketsu_ub', 0)
        model_instance.frfr_l_boketsu = row.get('frfr_l_boketsu_ub', 0)
        model_instance.apron_r_boketsu = row.get('apron_r_boketsu_ub', 0)
        model_instance.apron_l_boketsu = row.get('apron_l_boketsu_ub', 0)
        model_instance.inner_r_boketsu = row.get('inner_r_boketsu_ub', 0)
        model_instance.inner_l_boketsu = row.get('inner_l_boketsu_ub', 0)
        model_instance.frfr_r_shokusei_yobidashi = row.get('frfr_r_shokusei_yobidashi_ub', 0)
        model_instance.frfr_l_shokusei_yobidashi = row.get('frfr_l_shokusei_yobidashi_ub', 0)
        model_instance.apron_r_shokusei_yobidashi = row.get('apron_r_shokusei_yobidashi_ub', 0)
        model_instance.apron_l_shokusei_yobidashi = row.get('apron_l_shokusei_yobidashi_ub', 0)
        model_instance.inner_r_shokusei_yobidashi = row.get('inner_r_shokusei_yobidashi_ub', 0)
        model_instance.inner_l_shokusei_yobidashi = row.get('inner_l_shokusei_yobidashi_ub', 0)
        model_instance.frfr_r_sei_yobidashi = row.get('frfr_r_sei_yobidashi_ub', 0)
        model_instance.frfr_l_sei_yobidashi = row.get('frfr_l_sei_yobidashi_ub', 0)
        model_instance.apron_r_sei_yobidashi = row.get('apron_r_sei_yobidashi_ub', 0)
        model_instance.apron_l_sei_yobidashi = row.get('apron_l_sei_yobidashi_ub', 0)
        model_instance.inner_r_sei_yobidashi = row.get('inner_r_sei_yobidashi_ub', 0)
        model_instance.inner_l_sei_yobidashi = row.get('inner_l_sei_yobidashi_ub', 0)
        return model_instance

class UnderBodyPageData2Mapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = UnderBodyPageData2()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.fsmr_daisu = row.get('fsmr_daisu_ub', 0)
        model_instance.fsml_daisu = row.get('fsml_daisu_ub', 0)
        model_instance.dash_daisu = row.get('dash_daisu_ub', 0)
        model_instance.locker_daisu = row.get('locker_daisu_ub', 0)
        model_instance.rfloor_daisu = row.get('rfloor_daisu_ub', 0)
        model_instance.fsmr_em_time = row.get('fsmr_em_time_ub', 0)
        model_instance.fsml_em_time = row.get('fsml_em_time_ub', 0)
        model_instance.dash_em_time = row.get('dash_em_time_ub', 0)
        model_instance.locker_em_time = row.get('locker_em_time_ub', 0)
        model_instance.rfloor_em_time = row.get('rfloor_em_time_ub', 0)
        model_instance.fsmr_boman = row.get('fsmr_boman_ub', 0)
        model_instance.fsml_boman = row.get('fsml_boman_ub', 0)
        model_instance.dash_boman = row.get('dash_boman_ub', 0)
        model_instance.locker_boman = row.get('locker_boman_ub', 0)
        model_instance.rfloor_boman = row.get('rfloor_boman_ub', 0)
        model_instance.fsmr_boketsu = row.get('fsmr_boketsu_ub', 0)
        model_instance.fsml_boketsu = row.get('fsml_boketsu_ub', 0)
        model_instance.dash_boketsu = row.get('dash_boketsu_ub', 0)
        model_instance.locker_boketsu = row.get('locker_boketsu_ub', 0)
        model_instance.rfloor_boketsu = row.get('rfloor_boketsu_ub', 0)
        model_instance.fsmr_shokusei_yobidashi = row.get('fsmr_shokusei_yobidashi_ub', 0)
        model_instance.fsml_shokusei_yobidashi = row.get('fsml_shokusei_yobidashi_ub', 0)
        model_instance.dash_shokusei_yobidashi = row.get('dash_shokusei_yobidashi_ub', 0)
        model_instance.locker_shokusei_yobidashi = row.get('locker_shokusei_yobidashi_ub', 0)
        model_instance.rfloor_shokusei_yobidashi = row.get('rfloor_shokusei_yobidashi_ub', 0)
        model_instance.fsmr_sei_yobidashi = row.get('fsmr_sei_yobidashi_ub', 0)
        model_instance.fsml_sei_yobidashi = row.get('fsml_sei_yobidashi_ub', 0)
        model_instance.dash_sei_yobidashi = row.get('dash_sei_yobidashi_ub', 0)
        model_instance.locker_sei_yobidashi = row.get('locker_sei_yobidashi_ub', 0)
        model_instance.rfloor_sei_yobidashi = row.get('rfloor_sei_yobidashi_ub', 0)
        return model_instance

class UnderBodyPageData3Mapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = UnderBodyPageData3()
        model_instance = self.map_common_fields(row, model_instance)
        model_instance.noa_e_c_daisu = row.get('noa_e_c_daisu_ub', 0)
        model_instance.al_e_c_daisu = row.get('al_e_c_daisu_ub', 0)
        model_instance.noa_ctr_daisu = row.get('noa_ctr_daisu_ub', 0)
        model_instance.al_ctr_daisu = row.get('al_ctr_daisu_ub', 0)
        model_instance.noa_r_u_daisu = row.get('noa_r_u_daisu_ub', 0)
        model_instance.al_r_u_daisu = row.get('al_r_u_daisu_ub', 0)
        model_instance.noa_e_c_em_time = row.get('noa_e_c_em_time_ub', 0)
        model_instance.al_e_c_em_time = row.get('al_e_c_em_time_ub', 0)
        model_instance.noa_ctr_em_time = row.get('noa_ctr_em_time_ub', 0)
        model_instance.al_ctr_em_time = row.get('al_ctr_em_time_ub', 0)
        model_instance.noa_r_u_em_time = row.get('noa_r_u_em_time_ub', 0)
        model_instance.al_r_u_em_time = row.get('al_r_u_em_time_ub', 0)
        model_instance.noa_e_c_boman = row.get('noa_e_c_boman_ub', 0)
        model_instance.al_e_c_boman = row.get('al_e_c_boman_ub', 0)
        model_instance.noa_ctr_boman = row.get('noa_ctr_boman_ub', 0)
        model_instance.al_ctr_boman = row.get('al_ctr_boman_ub', 0)
        model_instance.noa_r_u_boman = row.get('noa_r_u_boman_ub', 0)
        model_instance.al_r_u_boman = row.get('al_r_u_boman_ub', 0)
        model_instance.noa_e_c_boketsu = row.get('noa_e_c_boketsu_ub', 0)
        model_instance.al_e_c_boketsu = row.get('al_e_c_boketsu_ub', 0)
        model_instance.noa_ctr_boketsu = row.get('noa_ctr_boketsu_ub', 0)
        model_instance.al_ctr_boketsu = row.get('al_ctr_boketsu_ub', 0)
        model_instance.noa_r_u_boketsu = row.get('noa_r_u_boketsu_ub', 0)
        model_instance.al_r_u_boketsu = row.get('al_r_u_boketsu_ub', 0)
        model_instance.noa_e_c_shokusei_yobidashi = row.get('noa_e_c_shokusei_yobidashi_ub', 0)
        model_instance.al_e_c_shokusei_yobidashi = row.get('al_e_c_shokusei_yobidashi_ub', 0)
        model_instance.noa_ctr_shokusei_yobidashi = row.get('noa_ctr_shokusei_yobidashi_ub', 0)
        model_instance.al_ctr_shokusei_yobidashi = row.get('al_ctr_shokusei_yobidashi_ub', 0)
        model_instance.noa_r_u_shokusei_yobidashi = row.get('noa_r_u_shokusei_yobidashi_ub', 0)
        model_instance.al_r_u_shokusei_yobidashi = row.get('al_r_u_shokusei_yobidashi_ub', 0)
        model_instance.noa_e_c_sei_yobidashi = row.get('noa_e_c_sei_yobidashi_ub', 0)
        model_instance.al_e_c_sei_yobidashi = row.get('al_e_c_sei_yobidashi_ub', 0)
        model_instance.noa_ctr_sei_yobidashi = row.get('noa_ctr_sei_yobidashi_ub', 0)
        model_instance.al_ctr_sei_yobidashi = row.get('al_ctr_sei_yobidashi_ub', 0)
        model_instance.noa_r_u_sei_yobidashi = row.get('noa_r_u_sei_yobidashi_ub', 0)
        model_instance.al_r_u_sei_yobidashi = row.get('al_r_u_sei_yobidashi_ub', 0)
        return model_instance
    

class UnderBodyPageData4Mapper(BaseMapper):
    def map_to_model(self, row):
        model_instance = UnderBodyPageData4()
        model_instance = self.map_common_fields(row, model_instance)
        
        model_instance.e_c_joku_daisu = row.get('e_c_joku_daisu_ub', 0)
        model_instance.ctr_joku_daisu = row.get('ctr_joku_daisu_ub', 0)
        model_instance.r_u_joku_daisu = row.get('r_u_joku_daisu_ub', 0)
        model_instance.motomachi_daisu = row.get('motomachi_daisu_ub', 0)
        
        model_instance.e_c_joku_em_time = row.get('e_c_joku_em_time_ub', 0)
        model_instance.ctr_joku_em_time = row.get('ctr_joku_em_time_ub', 0)
        model_instance.r_u_joku_em_time = row.get('r_u_joku_em_time_ub', 0)
        model_instance.motomachi_em_time = row.get('motomachi_em_time_ub', 0)
        
        model_instance.e_c_joku_boman = row.get('e_c_joku_boman_ub', 0)
        model_instance.ctr_joku_boman = row.get('ctr_joku_boman_ub', 0)
        model_instance.r_u_joku_boman = row.get('r_u_joku_boman_ub', 0)
        model_instance.motomachi_boman = row.get('motomachi_boman_ub', 0)
        
        model_instance.e_c_joku_boketsu = row.get('e_c_joku_boketsu_ub', 0)
        model_instance.ctr_joku_boketsu = row.get('ctr_joku_boketsu_ub', 0)
        model_instance.r_u_joku_boketsu = row.get('r_u_joku_boketsu_ub', 0)
        model_instance.motomachi_boketsu = row.get('motomachi_boketsu_ub', 0)
        
        model_instance.e_c_joku_shokusei_yobidashi = row.get('e_c_joku_shokusei_yobidashi_ub', 0)
        model_instance.ctr_joku_shokusei_yobidashi = row.get('ctr_joku_shokusei_yobidashi_ub', 0)
        model_instance.r_u_joku_shokusei_yobidashi = row.get('r_u_joku_shokusei_yobidashi_ub', 0)
        model_instance.motomachi_shokusei_yobidashi = row.get('motomachi_shokusei_yobidashi_ub', 0)
        
        model_instance.e_c_joku_sei_yobidashi = row.get('e_c_joku_sei_yobidashi_ub', 0)
        model_instance.ctr_joku_sei_yobidashi = row.get('ctr_joku_sei_yobidashi_ub', 0)
        model_instance.r_u_joku_sei_yobidashi = row.get('r_u_joku_sei_yobidashi_ub', 0)
        model_instance.motomachi_sei_yobidashi = row.get('motomachi_sei_yobidashi_ub', 0)

        return model_instance
